# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=50)),
                ('value', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('coefficient', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Variable'),
        ),
    ]
