# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20170304_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='stdev',
            field=models.FloatField(default=0),
        ),
    ]
