# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0004_variable_stdev'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='variable',
            name='coefficient',
        ),
        migrations.AddField(
            model_name='coefficient',
            name='variable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Variable'),
        ),
    ]
