# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20170309_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='mean',
            field=models.FloatField(default=0),
        ),
    ]
